// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conn.proto

package actor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ControlType int32

const (
	ControlType_CUnknown  ControlType = 0
	ControlType_CAuth     ControlType = 2
	ControlType_CSendName ControlType = 3
	ControlType_CAskName  ControlType = 4
	ControlType_CGetName  ControlType = 5
)

var ControlType_name = map[int32]string{
	0: "CUnknown",
	2: "CAuth",
	3: "CSendName",
	4: "CAskName",
	5: "CGetName",
}

var ControlType_value = map[string]int32{
	"CUnknown":  0,
	"CAuth":     2,
	"CSendName": 3,
	"CAskName":  4,
	"CGetName":  5,
}

func (x ControlType) String() string {
	return proto.EnumName(ControlType_name, int32(x))
}

func (ControlType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{0}
}

type ConnMessage struct {
	SequenceId           uint64       `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	Control              *ConnControl `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConnMessage) Reset()         { *m = ConnMessage{} }
func (m *ConnMessage) String() string { return proto.CompactTextString(m) }
func (*ConnMessage) ProtoMessage()    {}
func (*ConnMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{0}
}

func (m *ConnMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnMessage.Unmarshal(m, b)
}
func (m *ConnMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnMessage.Marshal(b, m, deterministic)
}
func (m *ConnMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnMessage.Merge(m, src)
}
func (m *ConnMessage) XXX_Size() int {
	return xxx_messageInfo_ConnMessage.Size(m)
}
func (m *ConnMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConnMessage proto.InternalMessageInfo

func (m *ConnMessage) GetSequenceId() uint64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func (m *ConnMessage) GetControl() *ConnControl {
	if m != nil {
		return m.Control
	}
	return nil
}

type ConnControl struct {
	Type                 ControlType `protobuf:"varint,1,opt,name=type,proto3,enum=actor.ControlType" json:"type,omitempty"`
	Auth                 *Auth       `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	SendName             *SendName   `protobuf:"bytes,3,opt,name=send_name,json=sendName,proto3" json:"send_name,omitempty"`
	AskName              *AskName    `protobuf:"bytes,4,opt,name=ask_name,json=askName,proto3" json:"ask_name,omitempty"`
	GetName              *GetName    `protobuf:"bytes,5,opt,name=get_name,json=getName,proto3" json:"get_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConnControl) Reset()         { *m = ConnControl{} }
func (m *ConnControl) String() string { return proto.CompactTextString(m) }
func (*ConnControl) ProtoMessage()    {}
func (*ConnControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{1}
}

func (m *ConnControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnControl.Unmarshal(m, b)
}
func (m *ConnControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnControl.Marshal(b, m, deterministic)
}
func (m *ConnControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnControl.Merge(m, src)
}
func (m *ConnControl) XXX_Size() int {
	return xxx_messageInfo_ConnControl.Size(m)
}
func (m *ConnControl) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnControl.DiscardUnknown(m)
}

var xxx_messageInfo_ConnControl proto.InternalMessageInfo

func (m *ConnControl) GetType() ControlType {
	if m != nil {
		return m.Type
	}
	return ControlType_CUnknown
}

func (m *ConnControl) GetAuth() *Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *ConnControl) GetSendName() *SendName {
	if m != nil {
		return m.SendName
	}
	return nil
}

func (m *ConnControl) GetAskName() *AskName {
	if m != nil {
		return m.AskName
	}
	return nil
}

func (m *ConnControl) GetGetName() *GetName {
	if m != nil {
		return m.GetName
	}
	return nil
}

type Auth struct {
	Req                  *Auth_Request  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Resp                 *Auth_Response `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{2}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

func (m *Auth) GetReq() *Auth_Request {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *Auth) GetResp() *Auth_Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

type Auth_Request struct {
	FromNodeId           uint32   `protobuf:"varint,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId             uint32   `protobuf:"varint,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	ConnName             string   `protobuf:"bytes,3,opt,name=conn_name,json=connName,proto3" json:"conn_name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_Request) Reset()         { *m = Auth_Request{} }
func (m *Auth_Request) String() string { return proto.CompactTextString(m) }
func (*Auth_Request) ProtoMessage()    {}
func (*Auth_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{2, 0}
}

func (m *Auth_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_Request.Unmarshal(m, b)
}
func (m *Auth_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_Request.Marshal(b, m, deterministic)
}
func (m *Auth_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_Request.Merge(m, src)
}
func (m *Auth_Request) XXX_Size() int {
	return xxx_messageInfo_Auth_Request.Size(m)
}
func (m *Auth_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_Request proto.InternalMessageInfo

func (m *Auth_Request) GetFromNodeId() uint32 {
	if m != nil {
		return m.FromNodeId
	}
	return 0
}

func (m *Auth_Request) GetToNodeId() uint32 {
	if m != nil {
		return m.ToNodeId
	}
	return 0
}

func (m *Auth_Request) GetConnName() string {
	if m != nil {
		return m.ConnName
	}
	return ""
}

func (m *Auth_Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Auth_Response struct {
	IsAuth               bool     `protobuf:"varint,1,opt,name=is_auth,json=isAuth,proto3" json:"is_auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_Response) Reset()         { *m = Auth_Response{} }
func (m *Auth_Response) String() string { return proto.CompactTextString(m) }
func (*Auth_Response) ProtoMessage()    {}
func (*Auth_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{2, 1}
}

func (m *Auth_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_Response.Unmarshal(m, b)
}
func (m *Auth_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_Response.Marshal(b, m, deterministic)
}
func (m *Auth_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_Response.Merge(m, src)
}
func (m *Auth_Response) XXX_Size() int {
	return xxx_messageInfo_Auth_Response.Size(m)
}
func (m *Auth_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_Response proto.InternalMessageInfo

func (m *Auth_Response) GetIsAuth() bool {
	if m != nil {
		return m.IsAuth
	}
	return false
}

type SendName struct {
	Req                  *SendName_Request  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Resp                 *SendName_Response `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SendName) Reset()         { *m = SendName{} }
func (m *SendName) String() string { return proto.CompactTextString(m) }
func (*SendName) ProtoMessage()    {}
func (*SendName) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{3}
}

func (m *SendName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendName.Unmarshal(m, b)
}
func (m *SendName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendName.Marshal(b, m, deterministic)
}
func (m *SendName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendName.Merge(m, src)
}
func (m *SendName) XXX_Size() int {
	return xxx_messageInfo_SendName.Size(m)
}
func (m *SendName) XXX_DiscardUnknown() {
	xxx_messageInfo_SendName.DiscardUnknown(m)
}

var xxx_messageInfo_SendName proto.InternalMessageInfo

func (m *SendName) GetReq() *SendName_Request {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *SendName) GetResp() *SendName_Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

type SendName_Request struct {
	FromId               uint32   `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName             string   `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	ToName               string   `protobuf:"bytes,3,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	SendData             *any.Any `protobuf:"bytes,4,opt,name=send_data,json=sendData,proto3" json:"send_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendName_Request) Reset()         { *m = SendName_Request{} }
func (m *SendName_Request) String() string { return proto.CompactTextString(m) }
func (*SendName_Request) ProtoMessage()    {}
func (*SendName_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{3, 0}
}

func (m *SendName_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendName_Request.Unmarshal(m, b)
}
func (m *SendName_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendName_Request.Marshal(b, m, deterministic)
}
func (m *SendName_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendName_Request.Merge(m, src)
}
func (m *SendName_Request) XXX_Size() int {
	return xxx_messageInfo_SendName_Request.Size(m)
}
func (m *SendName_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SendName_Request.DiscardUnknown(m)
}

var xxx_messageInfo_SendName_Request proto.InternalMessageInfo

func (m *SendName_Request) GetFromId() uint32 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *SendName_Request) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *SendName_Request) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *SendName_Request) GetSendData() *any.Any {
	if m != nil {
		return m.SendData
	}
	return nil
}

type SendName_Response struct {
	HasError             bool     `protobuf:"varint,1,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendName_Response) Reset()         { *m = SendName_Response{} }
func (m *SendName_Response) String() string { return proto.CompactTextString(m) }
func (*SendName_Response) ProtoMessage()    {}
func (*SendName_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{3, 1}
}

func (m *SendName_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendName_Response.Unmarshal(m, b)
}
func (m *SendName_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendName_Response.Marshal(b, m, deterministic)
}
func (m *SendName_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendName_Response.Merge(m, src)
}
func (m *SendName_Response) XXX_Size() int {
	return xxx_messageInfo_SendName_Response.Size(m)
}
func (m *SendName_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_SendName_Response.DiscardUnknown(m)
}

var xxx_messageInfo_SendName_Response proto.InternalMessageInfo

func (m *SendName_Response) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *SendName_Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type AskName struct {
	Req                  *AskName_Request  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Resp                 *AskName_Response `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AskName) Reset()         { *m = AskName{} }
func (m *AskName) String() string { return proto.CompactTextString(m) }
func (*AskName) ProtoMessage()    {}
func (*AskName) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{4}
}

func (m *AskName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskName.Unmarshal(m, b)
}
func (m *AskName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskName.Marshal(b, m, deterministic)
}
func (m *AskName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskName.Merge(m, src)
}
func (m *AskName) XXX_Size() int {
	return xxx_messageInfo_AskName.Size(m)
}
func (m *AskName) XXX_DiscardUnknown() {
	xxx_messageInfo_AskName.DiscardUnknown(m)
}

var xxx_messageInfo_AskName proto.InternalMessageInfo

func (m *AskName) GetReq() *AskName_Request {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *AskName) GetResp() *AskName_Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

type AskName_Request struct {
	FromId               uint32   `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName             string   `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	ToName               string   `protobuf:"bytes,3,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	AskData              *any.Any `protobuf:"bytes,4,opt,name=ask_data,json=askData,proto3" json:"ask_data,omitempty"`
	AnswerData           *any.Any `protobuf:"bytes,5,opt,name=answer_data,json=answerData,proto3" json:"answer_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskName_Request) Reset()         { *m = AskName_Request{} }
func (m *AskName_Request) String() string { return proto.CompactTextString(m) }
func (*AskName_Request) ProtoMessage()    {}
func (*AskName_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{4, 0}
}

func (m *AskName_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskName_Request.Unmarshal(m, b)
}
func (m *AskName_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskName_Request.Marshal(b, m, deterministic)
}
func (m *AskName_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskName_Request.Merge(m, src)
}
func (m *AskName_Request) XXX_Size() int {
	return xxx_messageInfo_AskName_Request.Size(m)
}
func (m *AskName_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_AskName_Request.DiscardUnknown(m)
}

var xxx_messageInfo_AskName_Request proto.InternalMessageInfo

func (m *AskName_Request) GetFromId() uint32 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *AskName_Request) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *AskName_Request) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *AskName_Request) GetAskData() *any.Any {
	if m != nil {
		return m.AskData
	}
	return nil
}

func (m *AskName_Request) GetAnswerData() *any.Any {
	if m != nil {
		return m.AnswerData
	}
	return nil
}

type AskName_Response struct {
	HasError             bool     `protobuf:"varint,1,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AnswerData           *any.Any `protobuf:"bytes,3,opt,name=answer_data,json=answerData,proto3" json:"answer_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskName_Response) Reset()         { *m = AskName_Response{} }
func (m *AskName_Response) String() string { return proto.CompactTextString(m) }
func (*AskName_Response) ProtoMessage()    {}
func (*AskName_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{4, 1}
}

func (m *AskName_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskName_Response.Unmarshal(m, b)
}
func (m *AskName_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskName_Response.Marshal(b, m, deterministic)
}
func (m *AskName_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskName_Response.Merge(m, src)
}
func (m *AskName_Response) XXX_Size() int {
	return xxx_messageInfo_AskName_Response.Size(m)
}
func (m *AskName_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_AskName_Response.DiscardUnknown(m)
}

var xxx_messageInfo_AskName_Response proto.InternalMessageInfo

func (m *AskName_Response) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *AskName_Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *AskName_Response) GetAnswerData() *any.Any {
	if m != nil {
		return m.AnswerData
	}
	return nil
}

type GetName struct {
	Req                  *GetName_Request  `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Resp                 *GetName_Response `protobuf:"bytes,2,opt,name=resp,proto3" json:"resp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetName) Reset()         { *m = GetName{} }
func (m *GetName) String() string { return proto.CompactTextString(m) }
func (*GetName) ProtoMessage()    {}
func (*GetName) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{5}
}

func (m *GetName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetName.Unmarshal(m, b)
}
func (m *GetName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetName.Marshal(b, m, deterministic)
}
func (m *GetName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetName.Merge(m, src)
}
func (m *GetName) XXX_Size() int {
	return xxx_messageInfo_GetName.Size(m)
}
func (m *GetName) XXX_DiscardUnknown() {
	xxx_messageInfo_GetName.DiscardUnknown(m)
}

var xxx_messageInfo_GetName proto.InternalMessageInfo

func (m *GetName) GetReq() *GetName_Request {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *GetName) GetResp() *GetName_Response {
	if m != nil {
		return m.Resp
	}
	return nil
}

type GetName_Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetName_Request) Reset()         { *m = GetName_Request{} }
func (m *GetName_Request) String() string { return proto.CompactTextString(m) }
func (*GetName_Request) ProtoMessage()    {}
func (*GetName_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{5, 0}
}

func (m *GetName_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetName_Request.Unmarshal(m, b)
}
func (m *GetName_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetName_Request.Marshal(b, m, deterministic)
}
func (m *GetName_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetName_Request.Merge(m, src)
}
func (m *GetName_Request) XXX_Size() int {
	return xxx_messageInfo_GetName_Request.Size(m)
}
func (m *GetName_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetName_Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetName_Request proto.InternalMessageInfo

func (m *GetName_Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetName_Response struct {
	Has                  bool     `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	ActorId              uint32   `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetName_Response) Reset()         { *m = GetName_Response{} }
func (m *GetName_Response) String() string { return proto.CompactTextString(m) }
func (*GetName_Response) ProtoMessage()    {}
func (*GetName_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{5, 1}
}

func (m *GetName_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetName_Response.Unmarshal(m, b)
}
func (m *GetName_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetName_Response.Marshal(b, m, deterministic)
}
func (m *GetName_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetName_Response.Merge(m, src)
}
func (m *GetName_Response) XXX_Size() int {
	return xxx_messageInfo_GetName_Response.Size(m)
}
func (m *GetName_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetName_Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetName_Response proto.InternalMessageInfo

func (m *GetName_Response) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

func (m *GetName_Response) GetActorId() uint32 {
	if m != nil {
		return m.ActorId
	}
	return 0
}

func init() {
	proto.RegisterEnum("actor.ControlType", ControlType_name, ControlType_value)
	proto.RegisterType((*ConnMessage)(nil), "actor.ConnMessage")
	proto.RegisterType((*ConnControl)(nil), "actor.ConnControl")
	proto.RegisterType((*Auth)(nil), "actor.Auth")
	proto.RegisterType((*Auth_Request)(nil), "actor.Auth.Request")
	proto.RegisterType((*Auth_Response)(nil), "actor.Auth.Response")
	proto.RegisterType((*SendName)(nil), "actor.SendName")
	proto.RegisterType((*SendName_Request)(nil), "actor.SendName.Request")
	proto.RegisterType((*SendName_Response)(nil), "actor.SendName.Response")
	proto.RegisterType((*AskName)(nil), "actor.AskName")
	proto.RegisterType((*AskName_Request)(nil), "actor.AskName.Request")
	proto.RegisterType((*AskName_Response)(nil), "actor.AskName.Response")
	proto.RegisterType((*GetName)(nil), "actor.GetName")
	proto.RegisterType((*GetName_Request)(nil), "actor.GetName.Request")
	proto.RegisterType((*GetName_Response)(nil), "actor.GetName.Response")
}

func init() { proto.RegisterFile("conn.proto", fileDescriptor_f401a58c1fc7ceef) }

var fileDescriptor_f401a58c1fc7ceef = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0xc7, 0xbf, 0xb4, 0x69, 0x93, 0x9c, 0x6e, 0xfb, 0x2a, 0x33, 0xd1, 0xae, 0x03, 0x6d, 0xea,
	0x04, 0x2a, 0x30, 0x65, 0x62, 0x08, 0x71, 0x3d, 0x15, 0x84, 0x26, 0xc1, 0x24, 0x3c, 0xb8, 0x43,
	0xaa, 0xbc, 0xc6, 0x6b, 0xa7, 0xad, 0x76, 0x17, 0xbb, 0xaa, 0x7a, 0x09, 0x5c, 0xf2, 0x24, 0xbc,
	0x01, 0x77, 0xf0, 0x1c, 0x3c, 0x0d, 0xf2, 0xb1, 0xd3, 0x24, 0x1b, 0x82, 0x5d, 0xc0, 0x9d, 0xed,
	0xff, 0x3f, 0xce, 0x39, 0xbf, 0x73, 0x8e, 0x01, 0x86, 0x52, 0x88, 0x78, 0x9a, 0x4a, 0x2d, 0x49,
	0x8d, 0x0d, 0xb5, 0x4c, 0x3b, 0x1b, 0x23, 0x29, 0x47, 0x17, 0x7c, 0x0f, 0x0f, 0x4f, 0x66, 0xa7,
	0x7b, 0x4c, 0x2c, 0xac, 0xa3, 0xfb, 0x1e, 0x1a, 0x7d, 0x29, 0xc4, 0x6b, 0xae, 0x14, 0x1b, 0x71,
	0xb2, 0x05, 0x0d, 0xc5, 0x2f, 0x67, 0x5c, 0x0c, 0xf9, 0xe0, 0x2c, 0x69, 0x7b, 0xdb, 0x5e, 0xcf,
	0xa7, 0x90, 0x1d, 0x1d, 0x26, 0x64, 0x17, 0x82, 0xa1, 0x14, 0x3a, 0x95, 0x17, 0xed, 0xca, 0xb6,
	0xd7, 0x6b, 0xec, 0x93, 0x18, 0xff, 0x11, 0x9b, 0x5b, 0xfa, 0x56, 0xa1, 0x99, 0xa5, 0xfb, 0xc3,
	0xb3, 0xd7, 0x3b, 0x81, 0xdc, 0x07, 0x5f, 0x2f, 0xa6, 0x1c, 0xef, 0x5d, 0x2b, 0x7e, 0x6a, 0xd4,
	0xb7, 0x8b, 0x29, 0xa7, 0xa8, 0x93, 0x2d, 0xf0, 0xd9, 0x4c, 0x8f, 0xdd, 0x2f, 0x1a, 0xce, 0x77,
	0x30, 0xd3, 0x63, 0x8a, 0x02, 0xd9, 0x85, 0x48, 0x71, 0x91, 0x0c, 0x04, 0x9b, 0xf0, 0x76, 0x15,
	0x5d, 0xff, 0x3b, 0xd7, 0x31, 0x17, 0xc9, 0x11, 0x9b, 0x70, 0x1a, 0x2a, 0xb7, 0x22, 0x0f, 0x20,
	0x64, 0xea, 0xdc, 0x9a, 0x7d, 0x34, 0xaf, 0x65, 0x57, 0xaa, 0x73, 0xf4, 0x06, 0xcc, 0x2e, 0x8c,
	0x75, 0xc4, 0xb5, 0xb5, 0xd6, 0x4a, 0xd6, 0x97, 0x5c, 0x5b, 0xeb, 0xc8, 0x2e, 0xba, 0x1f, 0x2a,
	0xe0, 0x9b, 0x90, 0xc8, 0x3d, 0xa8, 0xa6, 0xfc, 0x12, 0x93, 0x6a, 0xec, 0xdf, 0x2a, 0x04, 0x1b,
	0x53, 0x03, 0x4e, 0x69, 0x6a, 0x74, 0xd2, 0x03, 0x3f, 0xe5, 0x6a, 0xea, 0x92, 0x5a, 0x2f, 0xfb,
	0xd4, 0x54, 0x0a, 0xc5, 0x29, 0x3a, 0x3a, 0x1f, 0x3d, 0x08, 0xdc, 0xa7, 0x64, 0x1b, 0x56, 0x4e,
	0x53, 0x39, 0x19, 0x08, 0x99, 0x2c, 0x4b, 0xb2, 0x4a, 0xc1, 0x9c, 0x1d, 0xc9, 0xc4, 0x94, 0xe4,
	0x0e, 0x80, 0x96, 0x4b, 0xbd, 0x82, 0x7a, 0xa8, 0xa5, 0x53, 0x37, 0x21, 0x32, 0x0d, 0x91, 0x93,
	0x8a, 0x68, 0x68, 0x0e, 0x30, 0xdb, 0x0e, 0x84, 0x53, 0xa6, 0xd4, 0x5c, 0xa6, 0x09, 0x82, 0x89,
	0xe8, 0x72, 0xdf, 0xd9, 0x81, 0x30, 0x0b, 0x8b, 0xb4, 0x20, 0x38, 0x53, 0x03, 0x2c, 0x89, 0xf9,
	0x7f, 0x48, 0xeb, 0x67, 0xca, 0x04, 0xde, 0xfd, 0x56, 0x81, 0xf0, 0x38, 0xc7, 0x5c, 0xe0, 0xd0,
	0xba, 0x52, 0x8e, 0x32, 0x8b, 0xdd, 0x12, 0x8b, 0xf6, 0x75, 0x6f, 0x89, 0xc7, 0xe7, 0x02, 0x8f,
	0x16, 0x04, 0xc8, 0x63, 0x89, 0xa2, 0x6e, 0xb6, 0x36, 0x51, 0x0b, 0xca, 0x24, 0x5a, 0xb1, 0xc9,
	0x20, 0x25, 0x13, 0x5a, 0x0b, 0x02, 0xc3, 0x28, 0x67, 0x50, 0xd7, 0x12, 0x85, 0xc7, 0xae, 0x91,
	0x12, 0xa6, 0x99, 0xeb, 0x8d, 0xf5, 0xd8, 0x8e, 0x4b, 0x9c, 0x8d, 0x4b, 0x7c, 0x20, 0x16, 0xb6,
	0x9b, 0x9e, 0x33, 0xcd, 0x3a, 0xaf, 0x0a, 0x60, 0x36, 0x21, 0x1a, 0x33, 0x35, 0xe0, 0x69, 0x2a,
	0x53, 0x87, 0x26, 0x1c, 0x33, 0xf5, 0xc2, 0xec, 0xc9, 0x0e, 0xac, 0xa2, 0x30, 0x98, 0xd8, 0xe9,
	0x72, 0x51, 0xad, 0xe0, 0xa1, 0x9b, 0xb8, 0xee, 0x97, 0x2a, 0x04, 0xae, 0x0b, 0x49, 0xaf, 0x08,
	0xf0, 0x76, 0xb9, 0x45, 0xcb, 0xfc, 0x1e, 0x95, 0xf8, 0xb5, 0xae, 0x59, 0x4b, 0xf8, 0xbe, 0xff,
	0x3b, 0x7c, 0x7b, 0x76, 0xb2, 0xfe, 0x48, 0xcf, 0xcc, 0x97, 0x81, 0x47, 0x9e, 0x42, 0x83, 0x09,
	0x35, 0xe7, 0xa9, 0xfd, 0xa6, 0xf6, 0x9b, 0x6f, 0xc0, 0x1a, 0x91, 0xf9, 0x27, 0xef, 0x6f, 0x42,
	0xbf, 0x1a, 0x45, 0xf5, 0x66, 0x51, 0x74, 0xbf, 0x7a, 0x10, 0xb8, 0x67, 0xe0, 0xd7, 0xb5, 0x72,
	0xe2, 0x4d, 0x6a, 0x95, 0x5b, 0x4b, 0xb5, 0xba, 0x9b, 0x97, 0x8a, 0x80, 0x8f, 0xc4, 0x3d, 0x4c,
	0x00, 0xd7, 0x9d, 0x67, 0x05, 0x0c, 0x4d, 0xa8, 0x8e, 0x99, 0x72, 0x00, 0xcc, 0x92, 0x6c, 0x40,
	0x88, 0x97, 0xe7, 0xef, 0x40, 0x80, 0xfb, 0xc3, 0xe4, 0xe1, 0x1b, 0x7c, 0x88, 0xb3, 0x67, 0x96,
	0xac, 0x40, 0xd8, 0x7f, 0x27, 0xce, 0x85, 0x9c, 0x8b, 0xe6, 0x7f, 0x24, 0x82, 0x5a, 0xdf, 0x8c,
	0x73, 0xb3, 0x42, 0x56, 0x21, 0xea, 0x67, 0x63, 0xd8, 0xac, 0xa2, 0xcf, 0x75, 0x55, 0xd3, 0xc7,
	0x9d, 0x8b, 0xbb, 0x59, 0x3b, 0xa9, 0x23, 0xa7, 0x27, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x06,
	0x50, 0x2f, 0xfd, 0x71, 0x06, 0x00, 0x00,
}
