// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conn.proto

package actor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ControlType int32

const (
	ControlType_CUnknown  ControlType = 0
	ControlType_CAuth     ControlType = 2
	ControlType_CSendName ControlType = 3
	ControlType_CAskName  ControlType = 4
	ControlType_CGetName  ControlType = 5
)

var ControlType_name = map[int32]string{
	0: "CUnknown",
	2: "CAuth",
	3: "CSendName",
	4: "CAskName",
	5: "CGetName",
}

var ControlType_value = map[string]int32{
	"CUnknown":  0,
	"CAuth":     2,
	"CSendName": 3,
	"CAskName":  4,
	"CGetName":  5,
}

func (x ControlType) String() string {
	return proto.EnumName(ControlType_name, int32(x))
}

func (ControlType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{0}
}

type Direction int32

const (
	Direction_Request  Direction = 0
	Direction_Response Direction = 1
)

var Direction_name = map[int32]string{
	0: "Request",
	1: "Response",
}

var Direction_value = map[string]int32{
	"Request":  0,
	"Response": 1,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}

func (Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{1}
}

type DataType int32

const (
	DataType_ProtoBuf   DataType = 0
	DataType_Bool       DataType = 1
	DataType_Bytes      DataType = 2
	DataType_String     DataType = 3
	DataType_Int        DataType = 4
	DataType_Int8       DataType = 5
	DataType_Int16      DataType = 6
	DataType_Int32      DataType = 7
	DataType_Int64      DataType = 8
	DataType_UInt       DataType = 9
	DataType_UInt8      DataType = 10
	DataType_UInt16     DataType = 11
	DataType_UInt32     DataType = 12
	DataType_UInt64     DataType = 13
	DataType_Float32    DataType = 14
	DataType_Float64    DataType = 15
	DataType_Complex64  DataType = 16
	DataType_Complex128 DataType = 17
	DataType_Slice      DataType = 18
	DataType_Map        DataType = 19
)

var DataType_name = map[int32]string{
	0:  "ProtoBuf",
	1:  "Bool",
	2:  "Bytes",
	3:  "String",
	4:  "Int",
	5:  "Int8",
	6:  "Int16",
	7:  "Int32",
	8:  "Int64",
	9:  "UInt",
	10: "UInt8",
	11: "UInt16",
	12: "UInt32",
	13: "UInt64",
	14: "Float32",
	15: "Float64",
	16: "Complex64",
	17: "Complex128",
	18: "Slice",
	19: "Map",
}

var DataType_value = map[string]int32{
	"ProtoBuf":   0,
	"Bool":       1,
	"Bytes":      2,
	"String":     3,
	"Int":        4,
	"Int8":       5,
	"Int16":      6,
	"Int32":      7,
	"Int64":      8,
	"UInt":       9,
	"UInt8":      10,
	"UInt16":     11,
	"UInt32":     12,
	"UInt64":     13,
	"Float32":    14,
	"Float64":    15,
	"Complex64":  16,
	"Complex128": 17,
	"Slice":      18,
	"Map":        19,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}

func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{2}
}

type ConnMessage struct {
	SequenceId uint64      `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	Type       ControlType `protobuf:"varint,2,opt,name=type,proto3,enum=actor.ControlType" json:"type,omitempty"`
	Direction  Direction   `protobuf:"varint,3,opt,name=direction,proto3,enum=actor.Direction" json:"direction,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*ConnMessage_Auth
	//	*ConnMessage_GetName
	//	*ConnMessage_SendName
	//	*ConnMessage_AskName
	Content              isConnMessage_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConnMessage) Reset()         { *m = ConnMessage{} }
func (m *ConnMessage) String() string { return proto.CompactTextString(m) }
func (*ConnMessage) ProtoMessage()    {}
func (*ConnMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{0}
}

func (m *ConnMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnMessage.Unmarshal(m, b)
}
func (m *ConnMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnMessage.Marshal(b, m, deterministic)
}
func (m *ConnMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnMessage.Merge(m, src)
}
func (m *ConnMessage) XXX_Size() int {
	return xxx_messageInfo_ConnMessage.Size(m)
}
func (m *ConnMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConnMessage proto.InternalMessageInfo

func (m *ConnMessage) GetSequenceId() uint64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func (m *ConnMessage) GetType() ControlType {
	if m != nil {
		return m.Type
	}
	return ControlType_CUnknown
}

func (m *ConnMessage) GetDirection() Direction {
	if m != nil {
		return m.Direction
	}
	return Direction_Request
}

type isConnMessage_Content interface {
	isConnMessage_Content()
}

type ConnMessage_Auth struct {
	Auth *Auth `protobuf:"bytes,4,opt,name=auth,proto3,oneof"`
}

type ConnMessage_GetName struct {
	GetName *GetName `protobuf:"bytes,5,opt,name=get_name,json=getName,proto3,oneof"`
}

type ConnMessage_SendName struct {
	SendName *SendName `protobuf:"bytes,6,opt,name=send_name,json=sendName,proto3,oneof"`
}

type ConnMessage_AskName struct {
	AskName *AskName `protobuf:"bytes,7,opt,name=ask_name,json=askName,proto3,oneof"`
}

func (*ConnMessage_Auth) isConnMessage_Content() {}

func (*ConnMessage_GetName) isConnMessage_Content() {}

func (*ConnMessage_SendName) isConnMessage_Content() {}

func (*ConnMessage_AskName) isConnMessage_Content() {}

func (m *ConnMessage) GetContent() isConnMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ConnMessage) GetAuth() *Auth {
	if x, ok := m.GetContent().(*ConnMessage_Auth); ok {
		return x.Auth
	}
	return nil
}

func (m *ConnMessage) GetGetName() *GetName {
	if x, ok := m.GetContent().(*ConnMessage_GetName); ok {
		return x.GetName
	}
	return nil
}

func (m *ConnMessage) GetSendName() *SendName {
	if x, ok := m.GetContent().(*ConnMessage_SendName); ok {
		return x.SendName
	}
	return nil
}

func (m *ConnMessage) GetAskName() *AskName {
	if x, ok := m.GetContent().(*ConnMessage_AskName); ok {
		return x.AskName
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConnMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConnMessage_Auth)(nil),
		(*ConnMessage_GetName)(nil),
		(*ConnMessage_SendName)(nil),
		(*ConnMessage_AskName)(nil),
	}
}

type Auth struct {
	// Types that are valid to be assigned to Data:
	//	*Auth_Req
	//	*Auth_Resp
	Data                 isAuth_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Auth) Reset()         { *m = Auth{} }
func (m *Auth) String() string { return proto.CompactTextString(m) }
func (*Auth) ProtoMessage()    {}
func (*Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{1}
}

func (m *Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth.Unmarshal(m, b)
}
func (m *Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth.Marshal(b, m, deterministic)
}
func (m *Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth.Merge(m, src)
}
func (m *Auth) XXX_Size() int {
	return xxx_messageInfo_Auth.Size(m)
}
func (m *Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_Auth proto.InternalMessageInfo

type isAuth_Data interface {
	isAuth_Data()
}

type Auth_Req struct {
	Req *Auth_Request `protobuf:"bytes,1,opt,name=req,proto3,oneof"`
}

type Auth_Resp struct {
	Resp *Auth_Response `protobuf:"bytes,2,opt,name=resp,proto3,oneof"`
}

func (*Auth_Req) isAuth_Data() {}

func (*Auth_Resp) isAuth_Data() {}

func (m *Auth) GetData() isAuth_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Auth) GetReq() *Auth_Request {
	if x, ok := m.GetData().(*Auth_Req); ok {
		return x.Req
	}
	return nil
}

func (m *Auth) GetResp() *Auth_Response {
	if x, ok := m.GetData().(*Auth_Resp); ok {
		return x.Resp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Auth) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Auth_Req)(nil),
		(*Auth_Resp)(nil),
	}
}

type Auth_Request struct {
	FromNodeId           uint32   `protobuf:"varint,1,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	ToNodeId             uint32   `protobuf:"varint,2,opt,name=to_node_id,json=toNodeId,proto3" json:"to_node_id,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_Request) Reset()         { *m = Auth_Request{} }
func (m *Auth_Request) String() string { return proto.CompactTextString(m) }
func (*Auth_Request) ProtoMessage()    {}
func (*Auth_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{1, 0}
}

func (m *Auth_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_Request.Unmarshal(m, b)
}
func (m *Auth_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_Request.Marshal(b, m, deterministic)
}
func (m *Auth_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_Request.Merge(m, src)
}
func (m *Auth_Request) XXX_Size() int {
	return xxx_messageInfo_Auth_Request.Size(m)
}
func (m *Auth_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_Request proto.InternalMessageInfo

func (m *Auth_Request) GetFromNodeId() uint32 {
	if m != nil {
		return m.FromNodeId
	}
	return 0
}

func (m *Auth_Request) GetToNodeId() uint32 {
	if m != nil {
		return m.ToNodeId
	}
	return 0
}

func (m *Auth_Request) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Auth_Response struct {
	IsAuth               bool     `protobuf:"varint,1,opt,name=is_auth,json=isAuth,proto3" json:"is_auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Auth_Response) Reset()         { *m = Auth_Response{} }
func (m *Auth_Response) String() string { return proto.CompactTextString(m) }
func (*Auth_Response) ProtoMessage()    {}
func (*Auth_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{1, 1}
}

func (m *Auth_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Auth_Response.Unmarshal(m, b)
}
func (m *Auth_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Auth_Response.Marshal(b, m, deterministic)
}
func (m *Auth_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Auth_Response.Merge(m, src)
}
func (m *Auth_Response) XXX_Size() int {
	return xxx_messageInfo_Auth_Response.Size(m)
}
func (m *Auth_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Auth_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Auth_Response proto.InternalMessageInfo

func (m *Auth_Response) GetIsAuth() bool {
	if m != nil {
		return m.IsAuth
	}
	return false
}

type DataContentType struct {
	Type DataType `protobuf:"varint,1,opt,name=type,proto3,enum=actor.DataType" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*DataContentType_Proto
	//	*DataContentType_B
	//	*DataContentType_Bs
	//	*DataContentType_Str
	//	*DataContentType_I64
	//	*DataContentType_U64
	//	*DataContentType_F64
	Content              isDataContentType_Content `protobuf_oneof:"content"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *DataContentType) Reset()         { *m = DataContentType{} }
func (m *DataContentType) String() string { return proto.CompactTextString(m) }
func (*DataContentType) ProtoMessage()    {}
func (*DataContentType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{2}
}

func (m *DataContentType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataContentType.Unmarshal(m, b)
}
func (m *DataContentType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataContentType.Marshal(b, m, deterministic)
}
func (m *DataContentType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataContentType.Merge(m, src)
}
func (m *DataContentType) XXX_Size() int {
	return xxx_messageInfo_DataContentType.Size(m)
}
func (m *DataContentType) XXX_DiscardUnknown() {
	xxx_messageInfo_DataContentType.DiscardUnknown(m)
}

var xxx_messageInfo_DataContentType proto.InternalMessageInfo

func (m *DataContentType) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_ProtoBuf
}

type isDataContentType_Content interface {
	isDataContentType_Content()
}

type DataContentType_Proto struct {
	Proto *any.Any `protobuf:"bytes,2,opt,name=proto,proto3,oneof"`
}

type DataContentType_B struct {
	B bool `protobuf:"varint,3,opt,name=b,proto3,oneof"`
}

type DataContentType_Bs struct {
	Bs []byte `protobuf:"bytes,4,opt,name=bs,proto3,oneof"`
}

type DataContentType_Str struct {
	Str string `protobuf:"bytes,5,opt,name=str,proto3,oneof"`
}

type DataContentType_I64 struct {
	I64 int64 `protobuf:"varint,6,opt,name=i64,proto3,oneof"`
}

type DataContentType_U64 struct {
	U64 uint64 `protobuf:"varint,7,opt,name=u64,proto3,oneof"`
}

type DataContentType_F64 struct {
	F64 float64 `protobuf:"fixed64,8,opt,name=f64,proto3,oneof"`
}

func (*DataContentType_Proto) isDataContentType_Content() {}

func (*DataContentType_B) isDataContentType_Content() {}

func (*DataContentType_Bs) isDataContentType_Content() {}

func (*DataContentType_Str) isDataContentType_Content() {}

func (*DataContentType_I64) isDataContentType_Content() {}

func (*DataContentType_U64) isDataContentType_Content() {}

func (*DataContentType_F64) isDataContentType_Content() {}

func (m *DataContentType) GetContent() isDataContentType_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *DataContentType) GetProto() *any.Any {
	if x, ok := m.GetContent().(*DataContentType_Proto); ok {
		return x.Proto
	}
	return nil
}

func (m *DataContentType) GetB() bool {
	if x, ok := m.GetContent().(*DataContentType_B); ok {
		return x.B
	}
	return false
}

func (m *DataContentType) GetBs() []byte {
	if x, ok := m.GetContent().(*DataContentType_Bs); ok {
		return x.Bs
	}
	return nil
}

func (m *DataContentType) GetStr() string {
	if x, ok := m.GetContent().(*DataContentType_Str); ok {
		return x.Str
	}
	return ""
}

func (m *DataContentType) GetI64() int64 {
	if x, ok := m.GetContent().(*DataContentType_I64); ok {
		return x.I64
	}
	return 0
}

func (m *DataContentType) GetU64() uint64 {
	if x, ok := m.GetContent().(*DataContentType_U64); ok {
		return x.U64
	}
	return 0
}

func (m *DataContentType) GetF64() float64 {
	if x, ok := m.GetContent().(*DataContentType_F64); ok {
		return x.F64
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*DataContentType) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*DataContentType_Proto)(nil),
		(*DataContentType_B)(nil),
		(*DataContentType_Bs)(nil),
		(*DataContentType_Str)(nil),
		(*DataContentType_I64)(nil),
		(*DataContentType_U64)(nil),
		(*DataContentType_F64)(nil),
	}
}

type SendName struct {
	// Types that are valid to be assigned to Data:
	//	*SendName_Req
	//	*SendName_Resp
	Data                 isSendName_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SendName) Reset()         { *m = SendName{} }
func (m *SendName) String() string { return proto.CompactTextString(m) }
func (*SendName) ProtoMessage()    {}
func (*SendName) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{3}
}

func (m *SendName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendName.Unmarshal(m, b)
}
func (m *SendName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendName.Marshal(b, m, deterministic)
}
func (m *SendName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendName.Merge(m, src)
}
func (m *SendName) XXX_Size() int {
	return xxx_messageInfo_SendName.Size(m)
}
func (m *SendName) XXX_DiscardUnknown() {
	xxx_messageInfo_SendName.DiscardUnknown(m)
}

var xxx_messageInfo_SendName proto.InternalMessageInfo

type isSendName_Data interface {
	isSendName_Data()
}

type SendName_Req struct {
	Req *SendName_Request `protobuf:"bytes,1,opt,name=req,proto3,oneof"`
}

type SendName_Resp struct {
	Resp *SendName_Response `protobuf:"bytes,2,opt,name=resp,proto3,oneof"`
}

func (*SendName_Req) isSendName_Data() {}

func (*SendName_Resp) isSendName_Data() {}

func (m *SendName) GetData() isSendName_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SendName) GetReq() *SendName_Request {
	if x, ok := m.GetData().(*SendName_Req); ok {
		return x.Req
	}
	return nil
}

func (m *SendName) GetResp() *SendName_Response {
	if x, ok := m.GetData().(*SendName_Resp); ok {
		return x.Resp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SendName) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SendName_Req)(nil),
		(*SendName_Resp)(nil),
	}
}

type SendName_Request struct {
	FromId               uint32           `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName             string           `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	ToName               string           `protobuf:"bytes,3,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	SendData             *DataContentType `protobuf:"bytes,4,opt,name=send_data,json=sendData,proto3" json:"send_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SendName_Request) Reset()         { *m = SendName_Request{} }
func (m *SendName_Request) String() string { return proto.CompactTextString(m) }
func (*SendName_Request) ProtoMessage()    {}
func (*SendName_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{3, 0}
}

func (m *SendName_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendName_Request.Unmarshal(m, b)
}
func (m *SendName_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendName_Request.Marshal(b, m, deterministic)
}
func (m *SendName_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendName_Request.Merge(m, src)
}
func (m *SendName_Request) XXX_Size() int {
	return xxx_messageInfo_SendName_Request.Size(m)
}
func (m *SendName_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SendName_Request.DiscardUnknown(m)
}

var xxx_messageInfo_SendName_Request proto.InternalMessageInfo

func (m *SendName_Request) GetFromId() uint32 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *SendName_Request) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *SendName_Request) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *SendName_Request) GetSendData() *DataContentType {
	if m != nil {
		return m.SendData
	}
	return nil
}

type SendName_Response struct {
	HasError             bool     `protobuf:"varint,1,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendName_Response) Reset()         { *m = SendName_Response{} }
func (m *SendName_Response) String() string { return proto.CompactTextString(m) }
func (*SendName_Response) ProtoMessage()    {}
func (*SendName_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{3, 1}
}

func (m *SendName_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendName_Response.Unmarshal(m, b)
}
func (m *SendName_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendName_Response.Marshal(b, m, deterministic)
}
func (m *SendName_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendName_Response.Merge(m, src)
}
func (m *SendName_Response) XXX_Size() int {
	return xxx_messageInfo_SendName_Response.Size(m)
}
func (m *SendName_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_SendName_Response.DiscardUnknown(m)
}

var xxx_messageInfo_SendName_Response proto.InternalMessageInfo

func (m *SendName_Response) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *SendName_Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type AskName struct {
	// Types that are valid to be assigned to Data:
	//	*AskName_Req
	//	*AskName_Resp
	Data                 isAskName_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AskName) Reset()         { *m = AskName{} }
func (m *AskName) String() string { return proto.CompactTextString(m) }
func (*AskName) ProtoMessage()    {}
func (*AskName) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{4}
}

func (m *AskName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskName.Unmarshal(m, b)
}
func (m *AskName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskName.Marshal(b, m, deterministic)
}
func (m *AskName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskName.Merge(m, src)
}
func (m *AskName) XXX_Size() int {
	return xxx_messageInfo_AskName.Size(m)
}
func (m *AskName) XXX_DiscardUnknown() {
	xxx_messageInfo_AskName.DiscardUnknown(m)
}

var xxx_messageInfo_AskName proto.InternalMessageInfo

type isAskName_Data interface {
	isAskName_Data()
}

type AskName_Req struct {
	Req *AskName_Request `protobuf:"bytes,1,opt,name=req,proto3,oneof"`
}

type AskName_Resp struct {
	Resp *AskName_Response `protobuf:"bytes,2,opt,name=resp,proto3,oneof"`
}

func (*AskName_Req) isAskName_Data() {}

func (*AskName_Resp) isAskName_Data() {}

func (m *AskName) GetData() isAskName_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AskName) GetReq() *AskName_Request {
	if x, ok := m.GetData().(*AskName_Req); ok {
		return x.Req
	}
	return nil
}

func (m *AskName) GetResp() *AskName_Response {
	if x, ok := m.GetData().(*AskName_Resp); ok {
		return x.Resp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AskName) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AskName_Req)(nil),
		(*AskName_Resp)(nil),
	}
}

type AskName_Request struct {
	FromId               uint32           `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	FromName             string           `protobuf:"bytes,2,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	ToName               string           `protobuf:"bytes,3,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	AskData              *DataContentType `protobuf:"bytes,4,opt,name=ask_data,json=askData,proto3" json:"ask_data,omitempty"`
	AnswerData           *DataContentType `protobuf:"bytes,5,opt,name=answer_data,json=answerData,proto3" json:"answer_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AskName_Request) Reset()         { *m = AskName_Request{} }
func (m *AskName_Request) String() string { return proto.CompactTextString(m) }
func (*AskName_Request) ProtoMessage()    {}
func (*AskName_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{4, 0}
}

func (m *AskName_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskName_Request.Unmarshal(m, b)
}
func (m *AskName_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskName_Request.Marshal(b, m, deterministic)
}
func (m *AskName_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskName_Request.Merge(m, src)
}
func (m *AskName_Request) XXX_Size() int {
	return xxx_messageInfo_AskName_Request.Size(m)
}
func (m *AskName_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_AskName_Request.DiscardUnknown(m)
}

var xxx_messageInfo_AskName_Request proto.InternalMessageInfo

func (m *AskName_Request) GetFromId() uint32 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *AskName_Request) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *AskName_Request) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *AskName_Request) GetAskData() *DataContentType {
	if m != nil {
		return m.AskData
	}
	return nil
}

func (m *AskName_Request) GetAnswerData() *DataContentType {
	if m != nil {
		return m.AnswerData
	}
	return nil
}

type AskName_Response struct {
	HasError             bool             `protobuf:"varint,1,opt,name=has_error,json=hasError,proto3" json:"has_error,omitempty"`
	ErrorMessage         string           `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AnswerData           *DataContentType `protobuf:"bytes,3,opt,name=answer_data,json=answerData,proto3" json:"answer_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AskName_Response) Reset()         { *m = AskName_Response{} }
func (m *AskName_Response) String() string { return proto.CompactTextString(m) }
func (*AskName_Response) ProtoMessage()    {}
func (*AskName_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{4, 1}
}

func (m *AskName_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskName_Response.Unmarshal(m, b)
}
func (m *AskName_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskName_Response.Marshal(b, m, deterministic)
}
func (m *AskName_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskName_Response.Merge(m, src)
}
func (m *AskName_Response) XXX_Size() int {
	return xxx_messageInfo_AskName_Response.Size(m)
}
func (m *AskName_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_AskName_Response.DiscardUnknown(m)
}

var xxx_messageInfo_AskName_Response proto.InternalMessageInfo

func (m *AskName_Response) GetHasError() bool {
	if m != nil {
		return m.HasError
	}
	return false
}

func (m *AskName_Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *AskName_Response) GetAnswerData() *DataContentType {
	if m != nil {
		return m.AnswerData
	}
	return nil
}

type GetName struct {
	// Types that are valid to be assigned to Data:
	//	*GetName_Req
	//	*GetName_Resp
	Data                 isGetName_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetName) Reset()         { *m = GetName{} }
func (m *GetName) String() string { return proto.CompactTextString(m) }
func (*GetName) ProtoMessage()    {}
func (*GetName) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{5}
}

func (m *GetName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetName.Unmarshal(m, b)
}
func (m *GetName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetName.Marshal(b, m, deterministic)
}
func (m *GetName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetName.Merge(m, src)
}
func (m *GetName) XXX_Size() int {
	return xxx_messageInfo_GetName.Size(m)
}
func (m *GetName) XXX_DiscardUnknown() {
	xxx_messageInfo_GetName.DiscardUnknown(m)
}

var xxx_messageInfo_GetName proto.InternalMessageInfo

type isGetName_Data interface {
	isGetName_Data()
}

type GetName_Req struct {
	Req *GetName_Request `protobuf:"bytes,1,opt,name=req,proto3,oneof"`
}

type GetName_Resp struct {
	Resp *GetName_Response `protobuf:"bytes,2,opt,name=resp,proto3,oneof"`
}

func (*GetName_Req) isGetName_Data() {}

func (*GetName_Resp) isGetName_Data() {}

func (m *GetName) GetData() isGetName_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetName) GetReq() *GetName_Request {
	if x, ok := m.GetData().(*GetName_Req); ok {
		return x.Req
	}
	return nil
}

func (m *GetName) GetResp() *GetName_Response {
	if x, ok := m.GetData().(*GetName_Resp); ok {
		return x.Resp
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetName) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetName_Req)(nil),
		(*GetName_Resp)(nil),
	}
}

type GetName_Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetName_Request) Reset()         { *m = GetName_Request{} }
func (m *GetName_Request) String() string { return proto.CompactTextString(m) }
func (*GetName_Request) ProtoMessage()    {}
func (*GetName_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{5, 0}
}

func (m *GetName_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetName_Request.Unmarshal(m, b)
}
func (m *GetName_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetName_Request.Marshal(b, m, deterministic)
}
func (m *GetName_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetName_Request.Merge(m, src)
}
func (m *GetName_Request) XXX_Size() int {
	return xxx_messageInfo_GetName_Request.Size(m)
}
func (m *GetName_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetName_Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetName_Request proto.InternalMessageInfo

func (m *GetName_Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetName_Response struct {
	Has                  bool     `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	ActorId              uint32   `protobuf:"varint,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetName_Response) Reset()         { *m = GetName_Response{} }
func (m *GetName_Response) String() string { return proto.CompactTextString(m) }
func (*GetName_Response) ProtoMessage()    {}
func (*GetName_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f401a58c1fc7ceef, []int{5, 1}
}

func (m *GetName_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetName_Response.Unmarshal(m, b)
}
func (m *GetName_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetName_Response.Marshal(b, m, deterministic)
}
func (m *GetName_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetName_Response.Merge(m, src)
}
func (m *GetName_Response) XXX_Size() int {
	return xxx_messageInfo_GetName_Response.Size(m)
}
func (m *GetName_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetName_Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetName_Response proto.InternalMessageInfo

func (m *GetName_Response) GetHas() bool {
	if m != nil {
		return m.Has
	}
	return false
}

func (m *GetName_Response) GetActorId() uint32 {
	if m != nil {
		return m.ActorId
	}
	return 0
}

func (m *GetName_Response) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("actor.ControlType", ControlType_name, ControlType_value)
	proto.RegisterEnum("actor.Direction", Direction_name, Direction_value)
	proto.RegisterEnum("actor.DataType", DataType_name, DataType_value)
	proto.RegisterType((*ConnMessage)(nil), "actor.ConnMessage")
	proto.RegisterType((*Auth)(nil), "actor.Auth")
	proto.RegisterType((*Auth_Request)(nil), "actor.Auth.Request")
	proto.RegisterType((*Auth_Response)(nil), "actor.Auth.Response")
	proto.RegisterType((*DataContentType)(nil), "actor.DataContentType")
	proto.RegisterType((*SendName)(nil), "actor.SendName")
	proto.RegisterType((*SendName_Request)(nil), "actor.SendName.Request")
	proto.RegisterType((*SendName_Response)(nil), "actor.SendName.Response")
	proto.RegisterType((*AskName)(nil), "actor.AskName")
	proto.RegisterType((*AskName_Request)(nil), "actor.AskName.Request")
	proto.RegisterType((*AskName_Response)(nil), "actor.AskName.Response")
	proto.RegisterType((*GetName)(nil), "actor.GetName")
	proto.RegisterType((*GetName_Request)(nil), "actor.GetName.Request")
	proto.RegisterType((*GetName_Response)(nil), "actor.GetName.Response")
}

func init() { proto.RegisterFile("conn.proto", fileDescriptor_f401a58c1fc7ceef) }

var fileDescriptor_f401a58c1fc7ceef = []byte{
	// 979 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0xcd, 0x8e, 0xe3, 0x44,
	0x10, 0xc7, 0xe3, 0xd8, 0x89, 0xed, 0xca, 0xcc, 0x6c, 0xd3, 0x8b, 0x36, 0xd9, 0x2c, 0x88, 0x30,
	0x23, 0x2d, 0xa3, 0x00, 0x59, 0x4d, 0x26, 0x32, 0x7b, 0x9d, 0x64, 0x81, 0x44, 0x62, 0x57, 0xe0,
	0x61, 0x6e, 0x48, 0x91, 0x13, 0x77, 0x3e, 0x34, 0x49, 0x77, 0xd6, 0xdd, 0xd1, 0x90, 0x07, 0xe0,
	0xc8, 0x13, 0x21, 0x71, 0xe2, 0xca, 0x43, 0x70, 0xe4, 0xc4, 0x81, 0x17, 0x40, 0xd5, 0x6e, 0x3b,
	0x1f, 0x03, 0x68, 0x0e, 0x70, 0xab, 0xae, 0xfa, 0xb7, 0xbb, 0xba, 0x7e, 0xd5, 0x65, 0x80, 0xb1,
	0xe0, 0xbc, 0xb5, 0x4a, 0x84, 0x12, 0xb4, 0x14, 0x8d, 0x95, 0x48, 0xea, 0x4f, 0xa7, 0x42, 0x4c,
	0x17, 0xec, 0x85, 0x76, 0x8e, 0xd6, 0x93, 0x17, 0x11, 0xdf, 0xa4, 0x8a, 0xd3, 0x9f, 0x8b, 0x50,
	0xe9, 0x09, 0xce, 0x5f, 0x33, 0x29, 0xa3, 0x29, 0xa3, 0x1f, 0x40, 0x45, 0xb2, 0xb7, 0x6b, 0xc6,
	0xc7, 0x6c, 0x38, 0x8f, 0x6b, 0x56, 0xc3, 0x3a, 0x77, 0x42, 0xc8, 0x5c, 0x83, 0x98, 0x3e, 0x07,
	0x47, 0x6d, 0x56, 0xac, 0x56, 0x6c, 0x58, 0xe7, 0x27, 0x6d, 0xda, 0xd2, 0x27, 0xb4, 0x7a, 0x82,
	0xab, 0x44, 0x2c, 0xbe, 0xdd, 0xac, 0x58, 0xa8, 0xe3, 0xb4, 0x05, 0x7e, 0x3c, 0x4f, 0xd8, 0x58,
	0xcd, 0x05, 0xaf, 0xd9, 0x5a, 0x4c, 0x8c, 0xf8, 0x55, 0xe6, 0x0f, 0xb7, 0x12, 0xfa, 0x21, 0x38,
	0xd1, 0x5a, 0xcd, 0x6a, 0x4e, 0xc3, 0x3a, 0xaf, 0xb4, 0x2b, 0x46, 0x7a, 0xb5, 0x56, 0xb3, 0x7e,
	0x21, 0xd4, 0x21, 0xfa, 0x31, 0x78, 0x53, 0xa6, 0x86, 0x3c, 0x5a, 0xb2, 0x5a, 0x49, 0xcb, 0x4e,
	0x8c, 0xec, 0x4b, 0xa6, 0xde, 0x44, 0x4b, 0xd6, 0x2f, 0x84, 0xee, 0x34, 0x35, 0xf1, 0x7c, 0xc9,
	0x78, 0x9c, 0xaa, 0xcb, 0x5a, 0xfd, 0xc8, 0xa8, 0xaf, 0x19, 0x8f, 0x8d, 0xdc, 0x93, 0xc6, 0xc6,
	0x8f, 0x47, 0xf2, 0x36, 0x95, 0xbb, 0x7b, 0x1f, 0xbf, 0x92, 0xb7, 0xd9, 0xc7, 0xa3, 0xd4, 0xec,
	0xfa, 0xe0, 0x8e, 0x05, 0x57, 0x8c, 0xab, 0xd3, 0x3f, 0x2c, 0x70, 0x30, 0x4b, 0xfa, 0x11, 0xd8,
	0x09, 0x7b, 0xab, 0x2b, 0x56, 0x69, 0x3f, 0xde, 0xc9, 0xbf, 0x15, 0x62, 0xf5, 0xa4, 0xea, 0x17,
	0x42, 0x54, 0xd0, 0x26, 0x38, 0x09, 0x93, 0x2b, 0x5d, 0xc1, 0x4a, 0xfb, 0xdd, 0x7d, 0xa5, 0x5c,
	0x09, 0x2e, 0xf1, 0x2c, 0xad, 0xa9, 0x33, 0x70, 0xcd, 0x6e, 0xda, 0x80, 0xa3, 0x49, 0x22, 0x96,
	0x43, 0x2e, 0xe2, 0x1c, 0xcd, 0x71, 0x08, 0xe8, 0x7b, 0x23, 0x62, 0x44, 0xf3, 0x1e, 0x80, 0x12,
	0x79, 0xbc, 0xa8, 0xe3, 0x9e, 0x12, 0x26, 0x5a, 0x07, 0x6f, 0x15, 0x49, 0x79, 0x27, 0x92, 0x58,
	0xf3, 0xf0, 0xc3, 0x7c, 0x5d, 0x3f, 0x03, 0x2f, 0x3b, 0x9a, 0x56, 0xc1, 0x9d, 0xcb, 0xa1, 0x66,
	0x81, 0x47, 0x78, 0x61, 0x79, 0x2e, 0x31, 0xb9, 0x6e, 0x19, 0x9c, 0x38, 0x52, 0xd1, 0xe9, 0x6f,
	0x16, 0x3c, 0x7a, 0x15, 0xa9, 0xa8, 0x97, 0x56, 0x00, 0x99, 0xd3, 0x33, 0xd3, 0x15, 0x96, 0x06,
	0x9d, 0x15, 0x1a, 0x55, 0x3b, 0x2d, 0xf1, 0x09, 0x94, 0x74, 0xd3, 0xe5, 0x37, 0x4f, 0xdb, 0xb2,
	0x95, 0xb5, 0x65, 0xeb, 0x8a, 0x6f, 0xfa, 0x85, 0x30, 0x15, 0xd1, 0x13, 0xb0, 0x46, 0x3a, 0x51,
	0xaf, 0x5f, 0x08, 0xad, 0x11, 0x25, 0x50, 0x1c, 0x49, 0xdd, 0x1e, 0x47, 0xfd, 0x42, 0x58, 0x1c,
	0x49, 0x4a, 0xc1, 0x96, 0x2a, 0xd1, 0xad, 0xe0, 0x63, 0x71, 0xa5, 0x4a, 0xd0, 0x37, 0x0f, 0x3a,
	0x1a, 0xb8, 0x8d, 0xbe, 0x79, 0xd0, 0x41, 0xdf, 0x3a, 0xe8, 0x68, 0xaa, 0x0e, 0xfa, 0xd6, 0xa9,
	0x6f, 0x12, 0x74, 0x6a, 0x5e, 0xc3, 0x3a, 0xb7, 0xd0, 0x37, 0x09, 0x3a, 0xbb, 0x54, 0x7f, 0x2d,
	0x82, 0x77, 0xbd, 0x6d, 0x8d, 0x1d, 0xb2, 0xd5, 0x83, 0x26, 0x3a, 0xa4, 0xdb, 0xda, 0xa3, 0x5b,
	0xbb, 0xaf, 0x3e, 0x20, 0xfc, 0xa3, 0xb5, 0x45, 0x5c, 0x05, 0x57, 0x23, 0xce, 0xe9, 0x96, 0x71,
	0x39, 0x88, 0xe9, 0x33, 0xf0, 0x53, 0xf6, 0xd8, 0x9d, 0xc5, 0x14, 0x9e, 0x06, 0x8f, 0xe9, 0x55,
	0xc1, 0x45, 0xec, 0x18, 0x4a, 0xb9, 0x96, 0x95, 0xd0, 0x81, 0x4b, 0xf3, 0x04, 0x90, 0x9a, 0x79,
	0x57, 0x4f, 0x76, 0xc8, 0xec, 0xf0, 0x4b, 0xdf, 0x01, 0x3a, 0xeb, 0x5f, 0xed, 0xb4, 0xc2, 0x33,
	0xf0, 0x67, 0x91, 0x1c, 0xb2, 0x24, 0x11, 0x89, 0x69, 0x06, 0x6f, 0x16, 0xc9, 0xcf, 0x71, 0x4d,
	0xcf, 0xe0, 0x58, 0x07, 0x86, 0xcb, 0x74, 0x74, 0x98, 0xbc, 0x8e, 0xb4, 0xd3, 0x8c, 0x93, 0xbc,
	0x67, 0x7e, 0xb2, 0xc1, 0x35, 0xef, 0x88, 0x36, 0x77, 0xcb, 0xf9, 0x64, 0xff, 0x91, 0x1d, 0x56,
	0xf3, 0xd3, 0xbd, 0x6a, 0x56, 0xef, 0x89, 0x0f, 0x8a, 0xf9, 0xcb, 0xff, 0x57, 0xcc, 0x8b, 0x74,
	0x3e, 0x3c, 0xa0, 0x96, 0x38, 0x25, 0xd0, 0x47, 0x3f, 0x83, 0x4a, 0xc4, 0xe5, 0x1d, 0x4b, 0xd2,
	0x5d, 0xa5, 0x7f, 0xdd, 0x05, 0xa9, 0x54, 0x33, 0xf8, 0xc1, 0xfa, 0x2f, 0x21, 0x1c, 0xe6, 0x61,
	0x3f, 0x34, 0x8f, 0x9c, 0xde, 0xef, 0x16, 0xb8, 0x66, 0xc4, 0xfe, 0x3d, 0x3d, 0x13, 0x7c, 0x18,
	0xbd, 0xad, 0xf8, 0x80, 0xde, 0xfb, 0x5b, 0x78, 0x14, 0x1c, 0xcd, 0xc0, 0xd2, 0xd7, 0xd1, 0x76,
	0xfd, 0xbb, 0x9d, 0xa2, 0x10, 0xb0, 0x67, 0x91, 0x34, 0xe5, 0x40, 0x93, 0x3e, 0x05, 0x4f, 0x7f,
	0x7e, 0x3b, 0xfa, 0x5c, 0xbd, 0x1e, 0xc4, 0xf7, 0x8b, 0x64, 0xff, 0x73, 0xa7, 0x36, 0xbf, 0xd1,
	0xff, 0xc3, 0xec, 0x67, 0x46, 0x8f, 0xc0, 0xeb, 0xdd, 0xf0, 0x5b, 0x2e, 0xee, 0x38, 0x29, 0x50,
	0x1f, 0x4a, 0x3d, 0x9c, 0x85, 0xa4, 0x48, 0x8f, 0xc1, 0xef, 0x65, 0xaf, 0x9a, 0xd8, 0x5a, 0x67,
	0xda, 0x92, 0x38, 0x7a, 0x65, 0xae, 0x49, 0x4a, 0xcd, 0xe7, 0xe0, 0xe7, 0xbf, 0x3c, 0x5a, 0xc9,
	0x2f, 0x49, 0x0a, 0xa8, 0xcb, 0xae, 0x44, 0xac, 0xe6, 0x9f, 0x16, 0x78, 0xd9, 0xc8, 0xc4, 0xd0,
	0xd7, 0x38, 0x07, 0xbb, 0xeb, 0x09, 0x29, 0x50, 0x0f, 0x9c, 0xae, 0x10, 0x0b, 0x62, 0x61, 0x0a,
	0xdd, 0x8d, 0x62, 0x92, 0x14, 0x29, 0x40, 0xf9, 0x5a, 0x25, 0x73, 0x3e, 0x25, 0x36, 0x75, 0xc1,
	0x1e, 0x70, 0x45, 0x1c, 0x54, 0x0e, 0xb8, 0x7a, 0x49, 0x4a, 0xa8, 0x1c, 0x70, 0x75, 0x11, 0x90,
	0xb2, 0x31, 0x2f, 0xdb, 0xc4, 0x35, 0x66, 0xd0, 0x21, 0x1e, 0x4a, 0x6f, 0x70, 0x93, 0x8f, 0xce,
	0x1b, 0xbd, 0x0b, 0xf0, 0xa3, 0x37, 0xe9, 0xb6, 0x4a, 0x66, 0x5f, 0xb6, 0xc9, 0x51, 0x66, 0x07,
	0x1d, 0x72, 0x8c, 0x77, 0xf8, 0x62, 0x21, 0x22, 0x0c, 0x9c, 0xe4, 0x8b, 0xa0, 0x43, 0x1e, 0xe9,
	0xaa, 0x88, 0xe5, 0x6a, 0xc1, 0xbe, 0x0f, 0x3a, 0x84, 0xd0, 0x13, 0x00, 0xb3, 0xbc, 0x68, 0xbf,
	0x24, 0xef, 0xe0, 0x39, 0xd7, 0x8b, 0xf9, 0x98, 0x11, 0x8a, 0x09, 0xbf, 0x8e, 0x56, 0xe4, 0xf1,
	0xa8, 0xac, 0xc7, 0xfd, 0xe5, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x6a, 0x5c, 0x08, 0xb8,
	0x08, 0x00, 0x00,
}
